### ISSUE TITLE
SyntaxError upon analyzer.ph execution

### ISSUE THREAD

**Issue by marcel1337x** [Rafficer/reddit-analyzer#1]
Hello,

I get the following lines upon analyzer.ph execution:

`python analyzer.py -u xxxxx
  File "analyzer.py", line 75
    print('\033[93m' + "Fetched %d %s" % (total, switch2[option]) + '\033[0m', end="\r")
                                                                                                                              ^
SyntaxError: invalid syntax`

I also get the error with analyzer.ph -h

I'd be grateful for help! :)

**Comment by Rafficer** [comment]
What OS are you running?
Also what Python version?

**Comment by marcel1337x** [comment]
I am running Ubuntu 18.10

Python says
Python 2.7.15+ (default, Oct  2 2018, 22:12:08) 
[GCC 8.2.0] on linux2

**Comment by Rafficer** [comment]
The script is made for Python3.6+. Run it with `python3 analyzer.py -u xxxx` and it should work :)

**Comment by marcel1337x** [comment]
Oh! Thank you so much, it works with python3 :)
